# Generated by Django 5.2.12 on 2026-03-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citamedica',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Cita Médica', 'verbose_name_plural': 'Citas Médicas'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['apellido'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddConstraint(
            model_name='citamedica',
            constraint=models.UniqueConstraint(fields=('doctor', 'fecha', 'hora'), name='cita_unica_doctor'),
        ),
        migrations.AddConstraint(
            model_name='citamedica',
            constraint=models.UniqueConstraint(fields=('paciente', 'fecha', 'hora'), name='cita_unica_paciente'),
        ),
    ]
